### ISSUE TITLE
اعداد فارسی و هم‌عرض در نسخه متغیر

### ISSUE THREAD

**Issue by SepehrSepahi** [rastikerdar/vazirmatn#213]
لطفاً قابلیت‌هایی که طبق #198 افزوده شد، در نسخه متغیر هم تعبیه شود.

- نمایش فارسی اعداد غیرفارسی
- عرض یکسان برای اعداد

به صورت کلی خواهشمندم به نسخه متغیر فونت زیبای وزیر توجه بیشتری شود.

چرا که بی‌تردید مناسب‌ترین فونت جهت استفاده در وب، فونت با وزن متغیر است.

**Comment by rastikerdar** [comment]
اعداد هم‌عرض از طریق استایل‌ست‌ها فراهم شده. توی راهنمای فونت در موردش توضیح داده شده. در مرورگرها و همچنین در نسخه‌های اخیر برنامه‌ها پشتیبانی میشه.
https://rastikerdar.github.io/vazirmatn/fa/docs/HELP-fa

اعداد فارسی:
```css
.selector {
    font-feature-settings: "ss01";
}
```
اعداد هم‌عرض:
```css
.selector {
    font-feature-settings: "tnum";
}
```

هردو:
```css
.selector {
    font-feature-settings: "ss01", "tnum";
}
```
