### ISSUE TITLE
وسط نبودن کاراکتر ها موقع استفاده از حروف لاتین

### ISSUE THREAD

**Issue by saeedvaziry** [rastikerdar/vazirmatn#281]
توی نسخه وب و موقع هایلایت کردن نوشته ها:

کاراکتر های فارسی دقیقا وسط هستن ولی موقع استفاده از کاراکتر های لاتین یکم بالاتر قرار میگیرن.

<img width="645" alt="image" src="https://user-images.githubusercontent.com/61919774/180666582-76e73eb4-abce-41ce-a953-8958e48b2241.png">

<img width="786" alt="image" src="https://user-images.githubusercontent.com/61919774/180666600-5b21448e-f48b-4225-bc85-5216bfbbb549.png">

معمولا این مشکل رو با margin و یا line-height برطرف میکنم ولی وقتی قراره هم زبان فارسی هم انگلیسی ساپورت بشه بمشکل میخوره متاسفانه.

**Comment by rastikerdar** [comment]
همانطور که فرمودید فارسی مشکلی نداره. این تفاوت در ارتفاع فارسی و لاتین مشکل رایجی هست:
#264 
#110 
#209
#150

پیشنهاد من اینه که در وضعیت لاتین، از فونت روبوتو یا هر فونت لاتین دیگری استفاده کنید. یعنی در شرایطی که اولویت با لاتین باشه:
```css
.latin_el {
    font-family: Roboto, Vazirmatn, sans-serif;
}
```
در حالت فارسی:
```css
.farsi_el {
    font-family: Vazirmatn, Roboto, sans-serif;
}
```
